version: "3.7"

services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .

    image: dockertest

    container_name: dockertest

    ports:
      - "8080"

    restart: always

    volumes:
      - type: bind
        source: ${pwd}
        target: /dockertest/src
    command: npm run serve
