version: "3.7"

networks:
  vact-nest-network:
    name: app-tier

services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .

    image: dockertest

    container_name: dockertest

    stdin_open: true
    tty: true

    networks:
      - vact-nest-network

    ports:
      - "8080"

    restart: always

    volumes:
      - type: bind
        source: ${pwd}
        target: '/dockertest/src'

    command: npm run serve