version: "3.7"


services:
  dev:
    build:
      dockerfile: Dockerfile
      context: .

    image: dockerfile

    container_name: dockertest

    stdin_open: true
    tty: true

    ports:
      - "8080"

    restart: always

    volumes:
      - type: bind
        source: '${PWD}/src'
        target: '/dockerfile/src'

    command: ["node","/dockerfile/entrypoint.sh"]
